BaseConfig:
  Service:
    url: "gate.gb.ldt2023.infantem.tech"
    name: "gb-auth-gate"

  System:
    host: "0.0.0.0"
    port: "8000"
    max_goroutines: 15000

HttpConfig:
  time_out: 10
  accept: "application/json"
  do_log_requests: 1

LoggerConfig:
  Loki:
    host: "164.90.189.161"
    port: "3111"
    user: ""
    password: ""

SecureConfig:
  Fernet:
    key: ""

  RSA:
    public_key: ""
    private_key: ""